name: loop-rate-limiters
channels:
    - conda-forge
dependencies:
    - pip >=21.3.1
    - pip:
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-favicon
        - sphinx-mathjax-offline
        - sphinx-mdinclude
        - sphinx_rtd_theme
